services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ../auth/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

  auth-service:
    env_file:
      - auth-secret-key.env
    build:
      context: ..
      dockerfile: auth/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - database

  routing-service:
    build:
      context: ..
      dockerfile: routing/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - database

  photo-service:
    build:
      context: ..
      dockerfile: photo/Dockerfile
    ports:
      - "8083:8083"

volumes:
  database-data: